version: "3.9"
services:
  db:
    image: postgres:13.5
    container_name: postgres
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"